Repository scireum/token-autocomplete, pull requests merged in 2024-06, with the labels that each got.

#77 Improve alignment of token remove button and icon
  dist/token-autocomplete.css
  dist/token-autocomplete.js
  dist/token-autocomplete.js.map
  lib/token-autocomplete.ts
Labels: 🐛 Bugfix, 👶🏻 Trivial

#78 Position autocomplete suggestions absolutely
  dist/token-autocomplete.css
  dist/token-autocomplete.js
  dist/token-autocomplete.js.map
  lib/token-autocomplete.ts
Labels:  💣 BREAKING CHANGE, 🧬 Enhancement

#79 unify input-color to match with bootstrap .form-control
  dist/token-autocomplete.css
  dist/token-autocomplete.js.map
Labels: 🐛 Bugfix, 👶🏻 Trivial

#80 Remove forced min width of input field
  dist/token-autocomplete.css
  docs/index.html
Labels: 🐛 Bugfix, 👶🏻 Trivial

#81 Introduce a clear everything button in multiselect and search autocompletes
  README.md
  dist/token-autocomplete.css
  dist/token-autocomplete.js
  dist/token-autocomplete.js.map
  lib/token-autocomplete.ts
Labels:  💣 BREAKING CHANGE, 🧬 Enhancement

#82 SE-13734 fix remove-button for initial input and do not show on readonly
  dist/token-autocomplete.js
  dist/token-autocomplete.js.map
  lib/token-autocomplete.ts
Labels: 🐛 Bugfix, 🧬 Enhancement

#83 Embed SVG delete button icon in an IE 11 compatible way
  dist/token-autocomplete.css
Labels: 🐛 Bugfix, 👶🏻 Trivial

#84 Prevent the shrinking of the token delete button
  dist/token-autocomplete.css
  dist/token-autocomplete.js.map
Labels: 🐛 Bugfix
